/**
 * Constants for WCAG audit scripts
 */

// =============================================================================
// Auto-play Detection Constants
// =============================================================================

/** Screenshot intervals in milliseconds (0s, 2s, 4s, 6s) */
export const SCREENSHOT_INTERVALS = [0, 2000, 4000, 6000] as const;

/** Pixel change threshold (0.1% = significant change) */
export const CHANGE_THRESHOLD = 0.1;

/** Pixelmatch color difference threshold (0-1) */
export const PIXELMATCH_THRESHOLD = 0.1;

/** Wait time after clicking pause control (ms) */
export const PAUSE_CLICK_WAIT = 500;

/** Wait time between screenshots for comparison (ms) */
export const SCREENSHOT_COMPARISON_WAIT = 2000;

// =============================================================================
// Pause Control Detection Patterns
// =============================================================================

/** Keywords for pause/stop controls (EN/JP) */
export const PAUSE_KEYWORDS = [
  // English
  'pause', 'stop', 'halt', 'freeze', 'play',
  // Japanese
  '一時停止', '停止', 'ポーズ', '止める', '再生',
] as const;

/** Class name patterns indicating pause/play controls */
export const CONTROL_CLASS_PATTERNS = [
  'pause', 'play', 'stop', 'toggle', 'switch',
  'control', 'btn-pause', 'btn-play', 'btn-stop',
] as const;

/** Carousel-related class patterns */
export const CAROUSEL_PATTERNS = [
  'carousel', 'slider', 'slide', 'swiper', 'slick',
  'hero', 'banner', 'gallery', 'rotator',
] as const;

/** Navigation control keywords */
export const NAV_KEYWORDS = [
  'prev', 'next', '前', '次', 'arrow', 'dot', 'indicator',
] as const;

/** SVG metadata patterns to exclude from accessible names */
export const SVG_METADATA_PATTERNS = [
  'created with', 'made with', 'generated by',
  'svg', 'icon', 'symbol',
] as const;

/** Maximum parent levels to check for carousel context */
export const MAX_PARENT_LEVELS = 5;

// =============================================================================
// Focus Indicator Detection Constants
// =============================================================================

/** CSS properties to check for focus style changes */
export const FOCUS_STYLE_PROPERTIES = [
  'outline',
  'outlineColor',
  'outlineWidth',
  'outlineOffset',
  'boxShadow',
  'backgroundColor',
] as const;

/** Selector for focusable elements */
export const FOCUSABLE_SELECTOR = `
  input:not([type="hidden"]):not([disabled]),
  select:not([disabled]),
  textarea:not([disabled]),
  button:not([disabled]),
  a[href],
  [tabindex]:not([tabindex="-1"])
`.trim();

/** Extra tab iterations for safety margin */
export const EXTRA_TAB_ITERATIONS = 10;

// =============================================================================
// Output Paths
// =============================================================================

export const DEFAULT_AUTO_PLAY_OUTPUT_DIR = './auto-play-screenshots';
export const DEFAULT_FOCUS_OUTPUT_PATH = 'focus-indicators.png';
export const DETECTION_RESULT_FILENAME = 'detection-result.json';
